# Generated by Django 3.2.19 on 2023-05-22 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('phone_number', models.IntegerField()),
                ('email_address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Defects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('average_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('average_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bicycle_name', models.CharField(max_length=128)),
                ('bicycle_year', models.IntegerField()),
                ('priority', models.BooleanField()),
                ('estimated_time', models.DurationField()),
                ('notes', models.TextField()),
                ('expected_price', models.IntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('payment_in_advance', models.IntegerField()),
                ('reclamation', models.BooleanField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_task.clients')),
                ('defects', models.ManyToManyField(to='add_task.Defects')),
                ('employee_receiving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_employee', to='add_task.employees')),
                ('employee_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicing_employee', to='add_task.employees')),
                ('parts', models.ManyToManyField(to='add_task.Parts')),
            ],
        ),
    ]
