# Generated by Django 3.2.19 on 2023-05-24 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('phone_number', models.IntegerField()),
                ('email_address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Defects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('average_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=128)),
                ('average_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bicycle_name', models.CharField(max_length=128, null=True)),
                ('bicycle_year', models.IntegerField(null=True)),
                ('priority', models.BooleanField(null=True)),
                ('estimated_time', models.DurationField(null=True)),
                ('notes', models.TextField(null=True)),
                ('expected_price', models.IntegerField(null=True)),
                ('photo', models.ImageField(null=True, upload_to='')),
                ('payment_in_advance', models.IntegerField(null=True)),
                ('reclamation', models.BooleanField(null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_task.clients')),
            ],
        ),
        migrations.CreateModel(
            name='TasksParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_task.parts')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_task.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TasksDefects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_task.defects')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_task.tasks')),
            ],
        ),
        migrations.AddField(
            model_name='tasks',
            name='defects',
            field=models.ManyToManyField(null=True, through='add_task.TasksDefects', to='add_task.Defects'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='employee_receiving',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_employee', to='add_task.employees'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='employee_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicing_employee', to='add_task.employees'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='parts',
            field=models.ManyToManyField(null=True, through='add_task.TasksParts', to='add_task.Parts'),
        ),
    ]
