# Generated by Django 3.2.19 on 2023-05-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='bicycle_name',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='bicycle_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add_task.clients'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='defects',
            field=models.ManyToManyField(null=True, to='add_task.Defects'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='employee_receiving',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiving_employee', to='add_task.employees'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='employee_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servicing_employee', to='add_task.employees'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='estimated_time',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='expected_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='notes',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='parts',
            field=models.ManyToManyField(null=True, to='add_task.Parts'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='payment_in_advance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='photo',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='priority',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='reclamation',
            field=models.BooleanField(null=True),
        ),
    ]
