# Generated by Django 3.2.19 on 2023-05-23 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add_task', '0002_auto_20230523_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='TasksParts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_task.parts')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_task.tasks')),
            ],
        ),
        migrations.CreateModel(
            name='TasksDefects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_task.defects')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_task.tasks')),
            ],
        ),
        migrations.AlterField(
            model_name='tasks',
            name='defects',
            field=models.ManyToManyField(null=True, through='add_task.TasksDefects', to='add_task.Defects'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='parts',
            field=models.ManyToManyField(null=True, through='add_task.TasksParts', to='add_task.Parts'),
        ),
    ]
